versions:
  # Must conform to Semantic Versioning (https://semver.org/).
  # Should never need to use a pre-release suffix.
  specification: 3.1.0

  # Must be an Integer value.
  # Previously, prior to version 2 (i.e. versions 0.8, 1.0, 1.1 and 1.2) it was a Decimal value.
  protocol: 3
