name: Check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Read Node.js version
        id: tool-versions
        run: echo "nodejs=$(grep nodejs .tool-versions | awk '{print $2}')" >> $GITHUB_OUTPUT

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.tool-versions.outputs.nodejs }}

      - run: npm ci
        working-directory: build

      - run: npm run lint
        working-directory: build
